version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: control-asistencia-app
    ports:
      - "80:80"
    restart: unless-stopped
    environment:
      - NODE_ENV=production
